apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-livewebsocket
    release: ms-livewebsocket
  name: ms-livewebsockethttps-service
  namespace: backend
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: eurekaserverhttps
      nodePort: 32265
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: ms-livewebsocket
    release: ms-livewebsocket
  sessionAffinity: None
  type: LoadBalancer
